### ISSUE TITLE
no connection.on("event", function)

### ISSUE THREAD

**Issue by orefalo** [mafintosh/turbo-net#18]
all these call are failing when I try to add body-parser 

 stream.on('aborted', onAborted)
  stream.on('close', cleanup)
  stream.on('data', onData)
  stream.on('end', onEnd)
  stream.on('error', onEnd)

**Comment by LuKks** [comment]
Provide the complete code.

**Comment by orefalo** [comment]
Hi, thank for the reply: happy new year

well, I lost it as I tried to find a different solution to read the (chunked) request body.

In a nutshell, 
```
import { json } from "body-parser"
import * as polka from "polka"

  const app = polka()

  // parses incoming json post requests, and makes it available on req.body.
  app.use(json())

http.createServer(app.handler).listen(config.port, err => {})
```

basic setup right?

it fails with

```
.../node_modules/raw-body/index.js:190
  stream.on('aborted', onAborted)
         ^
TypeError: stream.on is not a function
    at readStream (/node_modules/raw-body/index.js:190:10)
    at getRawBody (/node_modules/raw-body/index.js:108:12)
    at read (/node_modules/body-parser/lib/read.js:77:3)
    at Array.jsonParser (/node_modules/body-parser/lib/types/json.js:135:5)
    at loop (/node_modules/polka/index.js:95:56)
    at Polka.handler (/node_modules/polka/index.js:98:3)
    at Server.emit (events.js:188:13)
    at Server.EventEmitter.emit (domain.js:441:20)
    at HTTPParser.onhead (/node_modules/turbo-http/lib/server.js:37:12)
    at HTTPParser.HEADER (/node_modules/http-parser-js/http-parser.js:338:58)
```

going deeper in the code, I figure the .on() methods above where missing.

**Comment by LuKks** [comment]
Thank you, you are very friendly.

I was seeing but don't seems compatible, also I was getting firstly other error but after fix that I get the error that you are commenting.

So to make it works, I did this only for your case and it's not the best way of do it. The important part is the middleware.
```javascript
let http = require('turbo-http');
let app = require('polka')();

//req.body
app.use((req, res, next) => {
  //make
  req.body = '';

  req.ondata = (buffer, start, length) => {
    req.body += buffer.toString('utf8').substr(start, length);
  }
  
  req.onend = () => {
    //parse
    if(req.body) {
      try {
        req.body = JSON.parse(req.body);
      }
      catch(err) {
        req.body = {};
      }
    }
    else {
      req.body = {};
    }

    //
    next();
  };
});

/**/
app.get('/', (req, res) => {
  res.setHeader('Content-Length', '5');
  res.write(Buffer.from('index'));
});

app.post('/', (req, res) => {
  console.log(req.body);

  res.setHeader('Content-Length', '8');
  res.write(Buffer.from('received'));
});

/**/
let server = http.createServer(app.handler);

server.listen(80, console.log);

/*
var xhr = new XMLHttpRequest();
xhr.open('POST', '/');
xhr.send(JSON.stringify({ username: 'LuKks' }));
*/
```

But you should care about the performance and limiting the body length.

Also you can't expect that turbo-net/http should be compatible with the most libraries.

By the way, this looks more related to turbo-http and this is turbo-net.

**Comment by orefalo** [comment]
Tks, will give it a try later today.

My use case is very simple, I am trying to build a high performance GraphqQL engine. I really like the 80k tps achieved by turbo-http & turbo-net

**Comment by orefalo** [comment]
It works, tks a bunch!
